# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biotop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'Biotope',
                'verbose_name_plural': 'Biotopes',
            },
        ),
        migrations.CreateModel(
            name='Dentition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='nom')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Dentition',
                'verbose_name_plural': 'Dentitions',
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'Distribution',
                'verbose_name_plural': 'Distributions',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=128, unique=True, verbose_name='Nom scientifique')),
                ('slug', models.SlugField(unique=True)),
                ('sex', models.CharField(help_text='format: n.n', max_length=33, verbose_name='Sexe')),
                ('birth', models.PositiveSmallIntegerField(help_text='Année uniquement', max_length=4, verbose_name='Né en')),
                ('reproduced', models.NullBooleanField(verbose_name="S'est déjà reproduit")),
                ('qt_born', models.PositiveSmallIntegerField(verbose_name='Nombre de naissance')),
                ('is_new_birth', models.NullBooleanField(verbose_name='Nouvelle naissance')),
                ('no_longer_own', models.NullBooleanField(verbose_name='Ancienne maintenance')),
                ('life_style', models.CharField(choices=[('A', 'Aube'), ('D', 'Diurne'), ('C', 'Crépusculaire'), ('N', 'Nocturne')], max_length=1, verbose_name='mode de vie')),
                ('description', models.TextField(blank=True)),
                ('business', models.CharField(blank=True, choices=[('A', 'Achat'), ('V', 'Vente'), ('E', 'Echange')], max_length=1, verbose_name='Ventes et achats')),
                ('price', models.FloatField(blank=True)),
                ('reproduction', models.CharField(choices=[('O', 'Ovipare'), ('V', 'Vivipare')], max_length=1)),
                ('is_venomous', models.NullBooleanField(verbose_name='Espèce venimeuse')),
                ('biotop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptiles.Biotop', verbose_name='Environnement')),
                ('dentition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptiles.Dentition')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptiles.Distribution', verbose_name='Air de répartition')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptiles.Family', verbose_name='Famille')),
            ],
            options={
                'verbose_name': 'Serpent',
                'verbose_name_plural': 'Serpents',
            },
        ),
        migrations.CreateModel(
            name='Venom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, unique=True, verbose_name='nom')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Venin',
                'verbose_name_plural': 'Venins',
            },
        ),
        migrations.AddField(
            model_name='snake',
            name='venom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptiles.Venom', verbose_name='Venin'),
        ),
    ]
